name: Publish package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish to Release
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5

    - name: Build
      run: >
        pip install -r build-requirements.txt
        && python -m build --wheel

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./dist/*.whl
        file_glob: true
